import type { Metadata } from "next";
import { Nunito_Sans, Paytone_One, Roboto } from "next/font/google";
import Header from "@/components/navbar/header";
import "./globals.css";
import {Providers} from "./providers";

const nunito = Nunito_Sans({ subsets: ["latin"] });
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

const paytone_One = Paytone_One({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
    <html lang="en" className='dark'>
      <body className={paytone_One.className + ' bg-[#1E1E1E] min-h-screen'}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}