import type { Metadata } from "next";
import { nunito, paytone_One } from "@/utilites/font";
import Header from "@/components/navbar/header";
import "./globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="dark">
			<body className={nunito.className + " bg-[#1E1E1E] min-h-screen"}>
				<Header />
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
